services:
  web:
    image: php:8.4-apache
    container_name: tes_web
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./deploy/apache/teploenergostroy.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
    command: >
      bash -lc "docker-php-ext-install intl pdo pdo_mysql && pecl install redis && docker-php-ext-enable redis && a2enmod rewrite && apache2-foreground"

  db:
    image: mariadb:10.11.13
    container_name: tes_db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: tes_site
      MARIADB_USER: tes_user
      MARIADB_PASSWORD: tes_password
      MARIADB_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: tes_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
